### ISSUE TITLE
Maybe there's no need for AbstractKafkaConsumer

### ISSUE THREAD

**Issue by mariojunior** [rajeshkumarbehura/ts-nestjs-kafka#5]
Hi Rajesh.
I was looking for something similar to @KafkaListener (Java Springboot) and your code is the most closer to it, thanks for that.

Reviewing your code, I noticed the only reason on having AbstractKafkaConsumer is making sure the inherited classes are able to register the topic into a map, where you keep a reference of the object (class) who owns the decorated function, then, based on the topic's name, you retrieve this object's reference when binding the consumer's handler to the decorated function, in order to use on "functionRef.apply(object, [ .... ])" at kafka.service.ts#L66

So, I think you don't need that, because the reference's object (class) is passed to the decorator's factory on the first argument *target* on kafka.decorator.ts#L6, if you store the target alongside the method's and topic's name, you'll have all you need for the functionRef.apply use.

That would be a simple change on your side and making way more simple for the usage of your lib, once the other developers won't need to inherit the abastract class and implement the registerTopic() method.

What do you reckon?

**Comment by rajeshkumarbehura** [comment]
Yes, you are right. I looked into the code and refactored it. Now it's more simple to use. Really thanks for your feedback.
